#!/bin/sh

########################################################################################################################
# Tut alles Richtige!
########################################################################################################################

print_usage() {
  printf "Usage: %s [options] <artifact_id>\n" "$(basename "$0")" 1>&2
  printf "Please specifiy the artifact to download errors for.\n" 1>&2
  exit 1
}

. configure.sh

execute_api_request_with_retry "api/v1/IntegrationRuntimeArtifacts('$ARTIFACT_ID')/ErrorInformation/"'$value'
if [ "$RESPONSE_CODE" = 200 ]; then

fi